apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-demo
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: py-demo
  template:
    metadata:
      labels:
        app: py-demo
    spec:
      containers:
        - name: web
          image: asia-south1-docker.pkg.dev/learning-2-465908/demopy/py-demo:v1
          ports:
            - containerPort: 8080
          # Probes help with reliable rollout
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
          # Autopilot: requests required
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: py-demo
  namespace: app
spec:
  type: LoadBalancer
  selector:
    app: py-demo
  ports:
    - port: 80
      targetPort: 8080
